# Dockerfile.frontend
FROM golang:1.16

WORKDIR /app

COPY go.mod .
COPY go.sum .

RUN go mod download
RUN go mod tidy

COPY frontend/ .

RUN go mod download
RUN go mod tidy
RUN go build -o main ./main.go

CMD ["./main"]