version: '3'
services:
  backend:
    build: 
      context: .
      dockerfile: ./backend/Dockerfile.backend
    ports:
      - 5000:5000
    depends_on:
      - db
      - cache
  frontend:
    build: 
      context: .
      dockerfile: ./frontend/Dockerfile.frontend
    ports:
      - 8080:8080
    depends_on:
      - backend
  db:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: 1234
      MYSQL_DATABASE: TestDB
    ports:
      - 3306:3306
  cache:
    image: redis:latest
    ports:
      - 6379:6379