# Dockerfile.backend
FROM golang:1.21.2-alpine

WORKDIR /app

COPY go.mod .
COPY go.sum .

RUN go mod download
RUN go mod tidy

COPY backend/ .
COPY entity2/ .
COPY myservice_pb/ .
COPY storage/ .
RUN go mod download
# RUN go get github.com/pvhop4dev/simple_microservices2/Entity/User
# RUN go get github.com/pvhop4dev/simple_microservices2/myservice_pb/myservice_pb
# RUN go get github.com/pvhop4dev/simple_microservices2/Storage/Redis
# RUN go get github.com/pvhop4dev/simple_microservices2/Storage/MySQL
# RUN go mod tidy

RUN go build -o main ./main.go

CMD ["./main"]